### ISSUE TITLE
app.json里的pages路径生成有误

### ISSUE THREAD

**Issue by bluefox1688** [meili/min-cli#1]
![qq 20171103105803](https://user-images.githubusercontent.com/11862797/32359257-a4272074-c087-11e7-9e00-cc14214a29d9.jpg)

在执行min dev后，小程序无法正常打开，查了下app.json里的配置，发现app.json里的pages路径生成有误，如截图，什么也没调整过。
window 10开发环境，NPM版本为4.6.1，node版本为6.10.1

**Comment by min-team** [comment]
windows 系统下的路径问题近期会解决，建议先使用 mac 系统。

**Comment by min-team** [comment]
@bluefox1688 windows系统的页面路径问题已修复，请将 Min Cli 升级到v1.0.2或最新版本

**Comment by bluefox1688** [comment]
好
