### ISSUE TITLE
修改全局模板，dev模式下没有编译所有文件

### ISSUE THREAD

**Issue by LancelotLewis** [meili/min-cli#10]
使用全局模板配置的时候，修改app.wxa的usingComponents内容，查看控制台只动态编译了app.wxa相关页面，没有动态编译所有wxp页面

操作系统：win10
min-cli：1.0.2
node：6.9.5

**Comment by min-team** [comment]
@LancelotLewis 收到，感谢反馈，min-team已经找到问题的原因，会尽快修复发布上线

**Comment by min-team** [comment]
@LancelotLewis Min Cli v1.0.3或最新版本已修复该问题
