### ISSUE TITLE
pages的设置问题

### ISSUE THREAD

**Issue by LoganJunjieSheng** [meili/min-cli#108]
我在app.wxa中做了如下配置，
pages: [
          "pages/test/index",
          "pages/home/index",
      ],
但在dev后在app.json中变成了这个样子
"pages": [
    "pages/home/index",
    "pages/test/index"
  ],

**Comment by mokeyjay** [comment]
这里面有说明啊 https://meili.github.io/min/docs/min-cli/app-project/dev/index.html

**Comment by LoganJunjieSheng** [comment]
!!感恩感恩。是我看文档不够仔细。
夸一句，minui的文档倒是我见过最好的小程序文档
