### ISSUE TITLE
style 标签中 import less文件默认查找wxss文件

### ISSUE THREAD

**Issue by LancelotLewis** [meili/min-cli#12]
如题描述
![image](https://user-images.githubusercontent.com/8749615/32650721-cbff7a8a-c639-11e7-9d32-0a15534671fb.png)
![image](https://user-images.githubusercontent.com/8749615/32650729-d446d6ac-c639-11e7-9da9-d97f19f766eb.png)

操作系统： win10
min-cli： 1.0.2
node： 6.9.5

**Comment by min-team** [comment]
@LancelotLewis 收到，感谢反馈，min-team会尽快修复

**Comment by LancelotLewis** [comment]
@min-team 能不能建一个微信群之类的，方便快速反馈确认bug

**Comment by min-team** [comment]
@LancelotLewis 这个问题涉及到底层编译改动较大，优化的方案有了，不过目前侧重优先修复紧急问题，关于这个问题后续我们会一直关注的

**Comment by min-team** [comment]
@LancelotLewis 微信群有了，方便加一下群吗？
[群二维码](https://s10.mogucdn.com//mlcdn/c45406/171127_33912geh7aeih110ah6hi9j56ejhf_752x974.jpg)

**Comment by LancelotLewis** [comment]
@cds803 更新1.0.5貌似还是不行，但是 dist 文件夹下已经生成了编程成 wxss 的文件，控制台的报错路径依然是 src 目录下
