### ISSUE TITLE
import 引入 'async-validator' 有误

### ISSUE THREAD

**Issue by LancelotLewis** [meili/min-cli#13]
贴图貌似一直失败，直接粘贴一下错误：
```
WAService.js:14 Uncaught Error: module "packages/async-validator/babel-runtime/core-js/object/core-js/library/fn/object/assign.js" is not defined
    at require (WAService.js:14)
    at WAService.js:14
    at assign.js? [sm]:1
    at require (WAService.js:14)
    at WAService.js:14
    at extends.js? [sm]:5
    at require (WAService.js:14)
    at WAService.js:14
    at index.js? [sm]:7
    at require (WAService.js:14)
```
确实是找不到这个路径，猜测原因是因为 import的包里还有import其他的包，多层循环导致路径叠加错误了。之前用的wepy解决方案是把所有import的包都平铺到第一层，当然这样会有包之间版本的问题，但是他们那种实现方式可以参考一下

![image](https://user-images.githubusercontent.com/8749615/32714941-1194d092-c88b-11e7-9165-b34f5e0014f3.png)
![image](https://user-images.githubusercontent.com/8749615/32714949-1c08fcba-c88b-11e7-8ba2-6f324748791b.png)
![image](https://user-images.githubusercontent.com/8749615/32714964-2928cad8-c88b-11e7-9bee-26a8a27c53e4.png)

**Comment by min-team** [comment]
@LancelotLewis 描述下使用的环境，node版本

**Comment by LancelotLewis** [comment]
@min-team sorry，一下忘了

操作系统： win10
min-cli： 1.0.2
node： 6.9.5

**Comment by min-team** [comment]
@LancelotLewis  Min Cli@1.0.3或最新版本已修复 import 第三方NPM包解析依赖路径的问题，不过import ‘async-validator’内部依赖包有使用process的node api，依然会存在错误。
![image](https://user-images.githubusercontent.com/32755767/32817388-f438d338-c982-11e7-82b5-94bb3bd94083.png)

**Comment by LancelotLewis** [comment]
@min-team 这个问题啥时候能完整解决啊，等着这个作表单验证功能了（要不你们推荐个能异步验证表单的js包也行）

**Comment by min-team** [comment]
@LancelotLewis 依赖第三方NPM包的编译解析问题已经修复了，你引用的 “async-validator” 应该是适用Node.js环境下，并不适合在小程序环境里运行

**Comment by LancelotLewis** [comment]
@min-team 我之前在 wepy 项目中是能够直接引用 `async-validator`并成功进行表单验证的，在浏览器中和在小程序中表现都一致。所以该模块应该是能够在浏览器和小程序环境下使用的，有没有可能是 min-cli 在处理打包过程中默认是以node环境为默认值，没有设置浏览器的标识，导致程序默认以node环境进行处理导致的错误？
