### ISSUE TITLE
button 组件的 formType 属性编译变成了小写

### ISSUE THREAD

**Issue by LancelotLewis** [meili/min-cli#15]
页面中所有组件的属性都默认使用转小写的方式进行了编译， 如下图所示：
![image](https://user-images.githubusercontent.com/8749615/32716905-baf8ae90-c892-11e7-879a-a166c58e0368.png)

猜测原因是提取template内容时使用了html的转换器，html里面属性就是不分大小写的。
操作系统： win10
min-cli： 1.0.2
node： 6.9.5

**Comment by Liumanyu** [comment]
这个问题我们已经修复了，但是根据微信小程序的官方文档，建议button 组件的form-type 属性不要使用驼峰式
[image](https://s10.mogucdn.com/mlcdn/c45406/171115_3005i22j3d1ad4hld15lj2dc6ej74_1076x224.png)

**Comment by LancelotLewis** [comment]
@Liumanyu 感谢，表单那部分代码我是直接复制官方示例代码的，没注意看button的属性列表
