### ISSUE TITLE
希望文档可以更丰富些

### ISSUE THREAD

**Issue by zzr7** [meili/min-cli#2]
使用起来特么爽，非常好用，文档不够完善。
比如min.config.json文件，还有app.wxa文件的配置说明。

**Comment by min-team** [comment]
@zzr7 好的

**Comment by Yukijethro** [comment]
最好有一些简单是视频教程，啃文档(希望能够更加详细)，有点儿啃不动，对于配置文件的说明，如果能配上注释就容易理解得多了

**Comment by min-team** [comment]
@zzr7 @Yukijethro Min 使用文档 https://meili.github.io/min/index.html，后续我们将推出视频教程。

**Comment by min-team** [comment]
@zzr7 @Yukijethro Min 使用文档 https://meili.github.io/min/index.html
