### ISSUE TITLE
src目录下非单文件的资源没有自动copy到dist目录下

### ISSUE THREAD

**Issue by LancelotLewis** [meili/min-cli#20]
在src目录下新建了一个statics文件里，里面存放一些图片和图标，在`min dev`或者`min build`时，dist目录下都没有自动生成对应的 statics 文件夹

操作系统： win10
min-cli： 1.0.3
node： 6.9.5

**Comment by min-team** [comment]
@LancelotLewis Min Cli工具是按照只对存在依赖引用的关系进行编译，也就是说按需打包功能，即使文件在src目录下，在没有被使用情况下不会拷贝到dist目录下

**Comment by LancelotLewis** [comment]
@min-team 是在image标签中写的本地图片地址，也没有自动复制进去

**Comment by min-team** [comment]
@LancelotLewis 感谢反馈，这是个BUG，建议先上传到cdn再使用，min-team会尽快修复

**Comment by Genuifx** [comment]
@min-team 使用webpack的copy插件可以事件将静态资源复制过去，cli要不要考虑添加这个功能

**Comment by min-team** [comment]
@Genuifx 感谢您的建议，后续cli会考虑这个功能的。由于之前只考虑到一些临时文件会增加小程序体积大小，另外一方面产生手动维护成本，所以Min Cli 在文件编译和拷贝上做了些优化，例如只会对有引用的文件进行编译和拷贝，而忽略掉了其他还有很多的场景情况

**Comment by dai875939260** [comment]
这个图片路径拷贝问题啥时候发布呢？

**Comment by cds803** [comment]
@LancelotLewis @Genuifx @dai875939260 请将Min Cli更新到1.0.6或最新版本

----------------------------------------------------------------------------
1.0.6版本增加
```
- style 样式引用本地字体图标文件
- wxp的template里可以引用本地图片、wxml和wxs文件
```

**Comment by xuxiaoxiao312** [comment]
最新版目前在image标签中写的本地图片地址可以自动copy到dist目录下，但是在wx.showToast中自定义图标的本地路径时引用的图片无法自动copy
`				wx.showToast({
					title: '生成订单失败，请重试',
					image: '../../assets/images/warn.png'
				})`

**Comment by Genuifx** [comment]
@xuxiaoxiao312 如果要支持到这种程度的话估计得全局匹配相关路径或者走ast编译了，暂时先手动放到static目录把

**Comment by zhlhuang** [comment]
组件的src 也不支持自动copy
