### ISSUE TITLE
wxc-tab 不能使用

### ISSUE THREAD

**Issue by jackyon** [meili/min-cli#24]
`'wxc-tab': '@minui/wxc-tab',
 'wxc-tab-panel': '@minui/wxc-tab/panel'`

我看到代码里头是需要引入panel的，但是我用 min install @minui/wxc-tab/panel 提示找部到安装包。

求解，谢谢。

实话说文档不是挺友好，我还有另外几个同事都花了不少时间在研究使用方法

**Comment by min-team** [comment]
@jackyon 收到，前期主要在功能实现上占据大部分时间，文档这块我们已经着手整理了

**Comment by min-team** [comment]
@jackyon 这个组件开发的时候虽然划分成了父子组件，但几个文件都放在tab目录下，@minui/wxc-tab/panel这个路径就是wxc-tab下的panel.js，panel.wxml, panel.wxss等文件，不需要再去install panel的，直接这样引用就行。很抱歉文档没有特别清晰给您带来的麻烦，有问题可以随时反馈的。

**Comment by min-team** [comment]
方便的话麻烦加一下微信群，有问题直接在群里反馈，谢谢！
[群二维码](https://s10.mogucdn.com//mlcdn/c45406/171127_33912geh7aeih110ah6hi9j56ejhf_752x974.jpg)

**Comment by min-team** [comment]
@jackyon 感谢你的反馈，目前已找到问题的原因，已经在修复了
------------------------------------------------------------------------------------------------
原因：理论上一个组件对外只暴露出一个入口，但是由于tab组件的特殊性，它对外提供了是多个入口，而 Min Cli 在编译的时候只关注了默认入口文件，所以我们讨论了下要对组件增加一项导出入口文件的配置，从而配合Min Cli进行按配置编译

**Comment by tinpont** [comment]
@min-team 现在还能加入微信群吗？

**Comment by cds803** [comment]
@happybobo wxc-tab组件支持多入口编译在 在v1.0.5 版本修复了，请更新最新版本再试

**Comment by cds803** [comment]
@tinpont 
![image](https://user-images.githubusercontent.com/387163/33872440-dd4878a6-df51-11e7-9d22-4e7fdedc890d.png)
