### ISSUE TITLE
编译时中文乱码问题

### ISSUE THREAD

**Issue by MrsHello** [meili/min-cli#27]
将app.wxa中的属性`navigationBarTitleText`设置为中文，编译后成为`????`，微信开发工具中接着会**编译报错**。

操作系统：win10
min-cli：1.0.4
node：6.9.2

**Comment by min-team** [comment]
@MrsHello 收到

**Comment by min-team** [comment]
@MrsHello 你好，在同样的环境下验证，并无编码问题，请确认下app.wxa文件编码是否为utf-8，或者排查下其他导致编码的一些相关问题

--------------------------------------------------------------------
图示：
app.wxa
![image](https://user-images.githubusercontent.com/32755767/33465069-ad9fa928-d680-11e7-8d85-dfc9600ed73a.png)

app.json
![image](https://user-images.githubusercontent.com/32755767/33465083-bc021050-d680-11e7-8c68-8413816c0212.png)
