### ISSUE TITLE
文档增加具体实例

### ISSUE THREAD

**Issue by tesths** [meili/min-cli#30]
因为不是专业的前端开发人员但是想使用 minui 的组件库。
文档看了几天虽然使用上了但是感觉还是有一定难度的，虽然 npm 是前端所需要掌握的，但是还是存在一定的使用门槛。
希望可以把文档的难度降下一点，或者是在不忙的情况下提供更为方便的调用接口以及编译好的文件，这样可以方便更多团队使用。

**Comment by min-team** [comment]
@tesths 好的，感谢你的建议，近期会推出一版新的文档，届时提提意见

**Comment by tesths** [comment]
不是感谢我的建议，应该感谢你们推出那么好的库。
非常好用后续项目都会使用的！
