### ISSUE TITLE
project.config.json每次启动min dev时都会被删

### ISSUE THREAD

**Issue by tinpont** [meili/min-cli#32]
微信开发工具的配置文件，在每次启动min dev的时候都会被删，里面需要存一下调试选项，这个怎么处理？

**Comment by cds803** [comment]
@tinpont 这是 min dev 下的一个bug，感谢你的反馈，会在下个版本里修复

**Comment by cds803** [comment]
@tinpont 这是 min dev 删除dist目录下所有文件的一个缺陷，感谢你的反馈，会在下个版本里修复

**Comment by cds803** [comment]
@tinpont 自MinCli 1.0.6版本开始，可以将project.config.json 配置文件放置在项目更目录下，在执行 `min dev` or `min build` 后，Min会将配置文件自动同步到dist目标目录下
