### ISSUE TITLE
修改app.wxp有时候会出现程序终止的情况

### ISSUE THREAD

**Issue by LancelotLewis** [meili/min-cli#33]
在修改完app.wxp文件时，几乎每次都会出现程序终止的情况，具体如下图：
![image](https://user-images.githubusercontent.com/8749615/33693647-ea6753bc-db2e-11e7-9cb2-41ce3187e275.png)
而且每次报错文件夹不为空的路径都不一样，是不是监听程序在删除文件夹的时候有小问题？

系统：Win10
node：8.9.0
min-cli：1.0.4

**Comment by cds803** [comment]
@LancelotLewis  在windows环境下，min dev 服务开启时，会先删除dist目录，此时小程序开发者工具占用着，请关闭小程序开发者工具后再试试

**Comment by LancelotLewis** [comment]
@cds803 我现在的做法是：使用nodemon管理开发环境，监听到app.wxp改动时，先进行删除`dist`目录下所有文件（如果直接删除dist文件夹会导致小程序开发工具监听dist文件夹失败），然后执行`min dev`，然后再执行`statics`文件夹复制的操作，这样也就解决了静态资源不自动复制的问题。但是这种方式只是暂时的hacker方式，真正完美的解决我觉得还是需要从底层去实现

**Comment by cds803** [comment]
@LancelotLewis 很棒~，静态资源同步问题已在计划中了，相信不久就可以用上了

**Comment by cds803** [comment]
@LancelotLewis 请更新MinCli到1.0.6或最新版本，静态资源同步问题已修复

**Comment by farzer** [comment]
语法错误有时候会直接崩，min-cli@1.0.7-beta.3
