### ISSUE TITLE
如何新建组件？

### ISSUE THREAD

**Issue by WalterZou** [meili/min-cli#34]
根据文档方法使用 `min init name` 只能建页面，如何新建组件呢？
看源码是可以设置 Type 的，并且设置了 Terminal 交互式问答，实际新建时并没有这个流程

**Comment by cds803** [comment]
@WalterZou min init 指令是用于初始化一个新的小程序或组件库项目的，新建页面或新建组件是通过 min new 指令，执行后命令行上可以选择新建类型

**Comment by WalterZou** [comment]
@cds803 测试在非根目录无法 new 出来，现在手动复制模板临时解决

**Comment by hustlrb** [comment]
@cds803 默认通过 `min init` 创建的小程序项目 `package.json` 里的内容为：
```
"minConfig": {
    "projectType": "application"
  }
```

需要将 `projectType` 改成 `component` 才可以通过 min new 新建组件，这是刻意设计成这样的吗？

min 工具很棒，赞一个 :)

**Comment by hustlrb** [comment]
OK，我知道了，这是项目类型决定的：） thx！
