### ISSUE TITLE
单文件组件编译提示「找不到入口」

### ISSUE THREAD

**Issue by WalterZou** [meili/min-cli#35]
文件目录如图：
![image](https://user-images.githubusercontent.com/3727208/33714657-b1eb6440-db8a-11e7-8c0f-e087b8cf32a4.png)
`min dev`  首次编译可以成功编译 icon.wxc 组件，但是修改后自动编译一直提示：
![image](https://user-images.githubusercontent.com/3727208/33714704-d71e34d6-db8a-11e7-94ea-d0294fe5e1ad.png)
请问这个是什么原因？如何解决？

**Comment by cds803** [comment]
@WalterZou 请升级 Min Cli 版本试试

**Comment by WalterZou** [comment]
@cds803 换 Mac 下开发没问题，先关闭了

**Comment by LancelotLewis** [comment]
@cds803 出现一样的问题。。。1.04、 1.0.5 都不行，降回1.0.3就没问题
系统：win10
min：1.0.5
node：8.9.5

**Comment by windpursuer** [comment]
@cds803 遇到一样的问题，求解决
系统：win10
min：1.0.5
node：8.9.3
