### ISSUE TITLE
关于 Less 编译支持的问题

### ISSUE THREAD

**Issue by WalterZou** [meili/min-cli#40]
*.wxp 单文件中用 lang=''less"  方法用 less 写样式时，编译会报错，如下：
```
// 示例代码
// index.wxp
<style lang="less">
@import '../../assets/styles/variables.less';
...
</style>
 // 或者
<style>
@import '../../assets/styles/variables.less';
...
</style>

// 都会报错
// 报错内容
[22:04:12] [编译] src/assets/styles/variables.less
[22:04:12] [ERROR] <css input>:1:1: Unknown word
```
看文档说支持 Less 的，但是目前貌似不行。另外，支持 PostCSS 的写法，都支持那些 PostCSS 插件呢？

**Comment by min-team** [comment]
@WalterZou less 代码部分是否包含了其他未知的关键字，请将完整的截图带上；PostCSS 目前默认支持 precss 和 postcss-bem 以及 px/rem 转 rpx 。https://meili.github.io/min/docs/features/style.html
