### ISSUE TITLE
Boolean类型属性转换问题

### ISSUE THREAD

**Issue by keepfool** [meili/min-cli#64]
微信小程序中，`Boolean`类型的属性，只要存在其值就为`true`，例如：
```html
<wxc-checkbox checked><wxc-checkbox>
```
但是min中新建的`wxp`文件，会将以上代码转换为
```html
<wxc-checkbox checked=""><wxc-checkbox>
```
这样`checked`就为`false`了，希望能修正此问题

**Comment by cds803** [comment]
@keepfool 试下1.0.7-beta.4版本
