### ISSUE TITLE
project.config.json使用miniprogramRoot配置项代替拷贝配置文件

### ISSUE THREAD

**Issue by tinpont** [meili/min-cli#66]
目前文档说明是使用“微信开发者工具”打开`dist`目录进行预览或上传。

实际上开发者工具提供miniprogramRoot选项指定源码目录，建议使用该选项代替拷贝project.config.json文件并直接打开dist目录。

直接打开dist目录存在问题：
    1. 开发者工具进行针对项目的一些配置无法保存（切换版本库，添加编译模式）
    2. 开发配置无法提交到git与共同开发者共享

参考官方文档：
> https://mp.weixin.qq.com/debug/wxadoc/dev/devtools/edit.html#%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by cds803** [comment]
@tinpont 👍，新版本采用这个方案

**Comment by cds803** [comment]
@mindev/min-cli@1.0.7-beta.6 已支持，体验下最新版本 @tinpont
