### ISSUE TITLE
与WePY框架结合时，安装组件报错

### ISSUE THREAD

**Issue by code-coder** [meili/min-cli#70]
WePY version -- 1.7.1
min version -- 1.0.6

+ **问题1：在与WePY框架结合时，安装组件报错，在dist/packages/@mimui/wxc-tost目录下就只有index.wxml和index.wxss文件生成，似乎没有index.wxs文件**

[15:50:00] [执行] npm install @minui/wxc-mask --save

npm WARN eslint-config-standard@7.1.0 requires a peer of eslint-plugin-promise@>=3.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN wepy-wechat-demo@1.0.0 No description
npm WARN wepy-wechat-demo@1.0.0 No repository field.

+ @minui/wxc-mask@1.0.8
updated 1 package in 7.322s

[15:50:09] [编译] node_modules/@minui/wxc-mask/src/index.wxc
[15:50:09] [写入] dist/packages/@minui/wxc-mask/dist/index.wxml
**[15:50:09] [ERROR] Unknown plugin "transform-decorators-legacy" specified in "base" at 2, attempted to resolve relative to "/Users/unicareer/Desktop/work/wepy/wepy-demo/node_modules/@minui/wxc-mask/src"**
[15:50:09] [写入] dist/packages/@minui/wxc-mask/dist/index.wxss

+ **问题2：小程序中调用事件时报Error: this.$wxpage.selectComponent is not a function**

**Comment by cds803** [comment]
缺少 babel plugin，babel-plugin-transform-decorators-legacy

**Comment by code-coder** [comment]
你好！这是我的min.config.json，我使用的教程的代码，里面有声明这个插件的，可是还是报找不到插件。
`{
  "compilers": { 
    "babel": {
      "sourceMaps": "inline",
      "presets": [
        "env"
      ],
      "plugins": [
        "syntax-export-extensions",
        "transform-class-properties",
        "transform-decorators-legacy",
        "transform-export-extensions"
      ]
    }
  },
  "npm": {
    "dest": "dist/packages"
  }
}`

babel-plugin-transform-decorators-legacy如何手动安装呢？

**Comment by code-coder** [comment]
你好！这是我的min.config.json，我使用的教程的代码，里面有声明这个插件的，可是还是报找不到插件。
```
{
  "compilers": {
    "babel": {
      "sourceMaps": "inline",
      "presets": [
        "env"
      ],
      "plugins": [
        "syntax-export-extensions",
        "transform-class-properties",
        "transform-decorators-legacy",
        "transform-export-extensions"
      ]
    }
  },
  "npm": {
    "dest": "dist/packages"
  }
}
```

是否需要手动安装babel-plugin-transform-decorators-legacy这个插件呢？

**Comment by cds803** [comment]
@code-coder  对的
