### ISSUE TITLE
在已有小程序项目中添加了toast组件，然后报错Cannot read property 'globalData' of undefined; 

### ISSUE THREAD

**Issue by Yuyg77** [meili/min-cli#74]
在已有小程序项目中添加了组件，然后报错Cannot read property 'globalData' of undefined; [Component] Property Observer Error @ dist/packages/@minui/wxc-toast/dist/index#observer
TypeError: Cannot read property 'globalData' of undefined

**Comment by cds803** [comment]
@Yuyg77 使用最新版本 toast 组件试试

**Comment by Yuyg77** [comment]
app.js不要为空就行了
