### ISSUE TITLE
组件引用路径正确，但是一直提示找不到组件

### ISSUE THREAD

**Issue by Yuyg77** [meili/min-cli#76]
![Uploading 微信图片_20180326104534.png…]()
error：Component is not found in path "dist/packsges/@minui/wxc-loading/dist/index" (using by "pages/bill/info/billinfo")

项目目录pages和dist是同级，pages/bill/info/billinfo这个是引用组件页面路径，组件路径dist/packsges/@minui/wxc-loading/dist/index
 "usingComponents":{
    "wxc-loading":"./../../../dist/packsges/@minui/wxc-loading/dist/index"
  }

**Comment by Penggggg** [comment]
@Yuyg77  遇到相同问题 请问你是怎么解决的呢
