### ISSUE TITLE
wepy引入minui无效

### ISSUE THREAD

**Issue by violinxliu** [meili/min-cli#82]
![image](https://user-images.githubusercontent.com/3621495/38814061-23f5a5d4-41c3-11e8-863e-1742e129d91b.png)
如图所示，没有报错，但是表现是不正确的。

**Comment by cds803** [comment]
未在page.json中注册wxc-elip组件
![image](https://user-images.githubusercontent.com/387163/38907132-e584e974-42ec-11e8-962f-8b2cbb2f1371.png)

请参考在已有项目中使用组件文档 https://meili.github.io/min/docs/min-cli/third-project/using/index.html

**Comment by hanwenbo** [comment]
我也是无效

**Comment by hanwenbo** [comment]
最后我一点点复制，用的这个网友写的解决了：https://github.com/jimmyrogue/wepy-X-minui

**Comment by violinxliu** [comment]
在wepy下，minui组件必须在wepy.page下引用。

**Comment by hanwenbo** [comment]
@violinxliu 好的多谢，wepy.component想都不用想是吧
